package com.example.harjoitustyo.web;

import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;

import com.example.harjoitustyo.domain.AppUser;
import com.example.harjoitustyo.domain.AppUserRepository;
import com.example.harjoitustyo.domain.City;
import com.example.harjoitustyo.domain.CityRepository;
import com.example.harjoitustyo.domain.Comment;
import com.example.harjoitustyo.domain.CommentRepository;
import com.example.harjoitustyo.domain.Location;
import com.example.harjoitustyo.domain.LocationRepository;
import com.example.harjoitustyo.domain.Region;
import com.example.harjoitustyo.domain.RegionRepository;

import jakarta.servlet.http.HttpServletRequest;

@Controller
public class DBController {

        private RegionRepository rRepository;
        private CityRepository cRepository;
        private LocationRepository lRepository;
        private CommentRepository coRepository;
        private AppUserRepository auRepository;

        public DBController(RegionRepository rRepository, CityRepository cRepository, LocationRepository lRepository,
                        CommentRepository coRepository, AppUserRepository auRepository) {

                this.rRepository = rRepository;
                this.cRepository = cRepository;
                this.lRepository = lRepository;
                this.coRepository = coRepository;
                this.auRepository = auRepository;
        }

        @PreAuthorize("hasAuthority('ADMIN')")
        @GetMapping(value = "/db/delete")
        public String deleteDB(Model model, HttpServletRequest request) {
                String referer = request.getHeader("Referer");
                coRepository.deleteAll();
                lRepository.deleteAll();
                cRepository.deleteAll();
                rRepository.deleteAll();
                auRepository.deleteAll();

                AppUser appUser1 = new AppUser("admin", "$2a$10$zNXa3MgyyUslVl.jL8950eGswQKEBKFVkSXlvghOPigjUcKXsasbK",
                                "adminTest", "userTestLast", "ADMIN");
                auRepository.save(appUser1);

                return "redirect:" + referer;
        }

        @PreAuthorize("hasAuthority('ADMIN')")
        @GetMapping(value = "/db/repopulate")
        public String repopulateDB(Model model, HttpServletRequest request) {
                String referer = request.getHeader("Referer");

                coRepository.deleteAll();
                lRepository.deleteAll();
                cRepository.deleteAll();
                rRepository.deleteAll();
                auRepository.deleteAll();

                Region region1 = new Region("Cmd: Test Region 1", "A region of test", "");
                Region region2 = new Region("Cmd: Test Region 2");
                // Region descriptions generated by ChatGPT
                Region rAhvenanmaa = new Region("Ahvenanmaa",
                                "Autonomous, Swedish-speaking archipelago known for maritime culture, ferries, and scenic islands.",
                                "https://upload.wikimedia.org/wikipedia/commons/5/5c/Coat_of_arms_of_%C3%85land.svg");
                Region rEtelaKarjala = new Region("Etelä-Karjala",
                                "Lake-rich southeastern region with Lappeenranta and Karelian culture near the Russian border.",
                                "https://upload.wikimedia.org/wikipedia/commons/9/91/Etel%C3%A4-Karjala.vaakuna.svg");
                Region rEtelaPohjanmaa = new Region("Etelä-Pohjanmaa",
                                "Open plains, strong traditions, and Ostrobothnian farm landscapes with lively rural festivals.",
                                "https://upload.wikimedia.org/wikipedia/commons/a/a8/Etel%C3%A4-Pohjanmaan_maakunnan_vaakuna.svg");
                Region rEtelaSavo = new Region("Etelä-Savo",
                                "Heart of the Finnish Lakeland, dotted with lakes and forests; home to Savonlinna.",
                                "https://upload.wikimedia.org/wikipedia/commons/6/6e/Etel%C3%A4-Savo.vaakuna.svg");
                Region rKainuu = new Region("Kainuu",
                                "Sparsely populated eastern region known for wilderness, hills, and nature tourism.",
                                "https://upload.wikimedia.org/wikipedia/commons/e/e5/Kainuu.vaakuna.svg");
                Region rKantaHame = new Region("Kanta-Häme",
                                "Historic inland region with Hämeenlinna, lakes, and medieval Häme Castle.",
                                "https://upload.wikimedia.org/wikipedia/commons/8/83/Kanta-H%C3%A4me.vaakuna.svg");
                Region rKeskiPohjanmaa = new Region("Keski-Pohjanmaa",
                                "Coastal plains region emphasizing agriculture, folk music, and small rural towns.",
                                "https://upload.wikimedia.org/wikipedia/commons/7/7f/Keski-Pohjanmaa.vaakuna.svg");
                Region rKeskiSuomi = new Region("Keski-Suomi",
                                "Central lake district with Jyväskylä, forest landscapes, and strong design and education heritage.",
                                "https://upload.wikimedia.org/wikipedia/commons/7/74/Keski-Suomi_Coat_of_Arms.svg");
                Region rKymenlaakso = new Region("Kymenlaakso",
                                "Southeastern coastal region focused on ports, rivers, and industrial history.",
                                "https://upload.wikimedia.org/wikipedia/commons/7/70/Kymenlaakson_maakunnan_vaakuna.svg");
                Region rLappi = new Region("Lappi",
                                "Finland’s Arctic north with Sámi culture, vast wilderness, fells, and Northern Lights.",
                                "https://upload.wikimedia.org/wikipedia/commons/c/c8/Lapin_maakunnan_vaakuna.svg");
                Region rPirkanmaa = new Region("Pirkanmaa",
                                "Vibrant region centered on Tampere, mixing industry, culture, and lake scenery.",
                                "https://upload.wikimedia.org/wikipedia/commons/c/c3/Pirkanmaa.vaakuna.svg");
                Region rPohjanmaa = new Region("Pohjanmaa",
                                "Bilingual coastal area with flat landscapes, wooden towns, and strong Swedish-Finnish heritage.",
                                "https://upload.wikimedia.org/wikipedia/commons/0/09/Pohjanmaan_maakunnan_vaakuna.svg");
                Region rPohjoisKarjala = new Region("Pohjois-Karjala",
                                "Forested eastern region known for Karelian cuisine, culture, and scenic hills.",
                                "https://upload.wikimedia.org/wikipedia/commons/6/66/Pohjois-Karjala.vaakuna.svg");
                Region rPohjoisPohjanmaa = new Region("Pohjois-Pohjanmaa",
                                "Northern region combining coastline, forests, and Oulu’s tech-driven urban life.",
                                "https://upload.wikimedia.org/wikipedia/commons/b/bd/Pohjois-Pohjanmaan_vaakuna.svg");
                Region rPohjoisSavo = new Region("Pohjois-Savo",
                                "Lakeland region around Kuopio, known for relaxed Savonian culture and lakes.",
                                "https://upload.wikimedia.org/wikipedia/commons/b/b4/Pohjois-Savo.vaakuna.svg");
                Region rPaijatHame = new Region("Päijät-Häme",
                                "Southern lake region with Lahti, sports traditions, and forested landscapes.",
                                "https://upload.wikimedia.org/wikipedia/commons/4/43/P%C3%A4ij%C3%A4t-H%C3%A4me.vaakuna.svg");
                Region rSatakunta = new Region("Satakunta",
                                "Southwestern coastal region mixing industry, agriculture, and historic towns like Pori.",
                                "https://upload.wikimedia.org/wikipedia/commons/d/d8/Satakunta.vaakuna.svg");
                Region rUusimaa = new Region("Uusimaa",
                                "Finland’s most populous region, including Helsinki; urban, international, and coastal.",
                                "https://upload.wikimedia.org/wikipedia/commons/f/f9/Uusimaa.vaakuna.svg");
                Region rVarsinaisSuomi = new Region("Varsinais-Suomi",
                                "Historic southwest region with Turku, archipelago nature, and early Finnish heritage.",
                                "https://upload.wikimedia.org/wikipedia/commons/f/f3/Varsinais-Suomen.vaakuna.svg");

                // City descriptions generated by ChatGPT
                City cAkaa = new City("Akaa", 16402, 293.29,
                                "Small Pirkanmaa town with lakes, industry, and peaceful rural surroundings.",
                                rPirkanmaa,
                                "https://upload.wikimedia.org/wikipedia/commons/5/52/Akaa.vaakuna.svg");
                City cAlajarvi = new City("Alajärvi", 9065, 1008.81,
                                "South Ostrobothnian town known for open landscapes and cultural heritage.",
                                rEtelaPohjanmaa,
                                "https://upload.wikimedia.org/wikipedia/commons/1/13/Alaj%C3%A4rvi.vaakuna.svg");
                City cAlavus = new City("Alavus", 10722, 1087.18,
                                "Lake-dotted rural town with strong local industry and traditions.", rEtelaPohjanmaa,
                                "https://upload.wikimedia.org/wikipedia/commons/6/62/T%C3%B6ys%C3%A4.vaakuna.svg");
                City cEspoo = new City("Espoo", 323910, 312.88,
                                "Large, innovative city with tech hubs, nature, and diverse districts.", rUusimaa,
                                "https://upload.wikimedia.org/wikipedia/commons/f/f6/Espoo.vaakuna.svg");
                City cForssa = new City("Forssa", 16368, 248.87,
                                "Historic textile town with parks, culture, and compact urban life.", rKantaHame,
                                "https://upload.wikimedia.org/wikipedia/commons/5/51/Forssan_vaakuna.svg");
                City cHaapajarvi = new City("Haapajärvi", 6482, 767.08,
                                "Northern lakeside town with agriculture, nature, and calm living.", rPohjoisPohjanmaa,
                                "https://upload.wikimedia.org/wikipedia/commons/a/a9/Haapaj%C3%A4rvi.vaakuna.svg");
                City cHaapavesi = new City("Haapavesi", 6347, 1050.69,
                                "Folk music traditions, rural scenery, and quiet small-town character.",
                                rPohjoisPohjanmaa,
                                "https://upload.wikimedia.org/wikipedia/commons/8/88/Haapavesi.vaakuna.svg");
                City cHamina = new City("Hamina", 19305, 609.89,
                                "Coastal fortress town known for circular town plan and maritime heritage.",
                                rKymenlaakso,
                                "https://upload.wikimedia.org/wikipedia/commons/e/ef/Hamina.vaakuna.svg");
                City cHanko = new City("Hanko", 7740, 117.6,
                                "Southern seaside town famous for beaches, sailing, and summer life.", rUusimaa,
                                "https://upload.wikimedia.org/wikipedia/commons/f/f1/Hanko.vaakuna.svg");
                City cHarjavalta = new City("Harjavalta", 6605, 123.48,
                                "Industrial riverside town known for metal production and nature areas.", rSatakunta,
                                "https://upload.wikimedia.org/wikipedia/commons/8/8a/Harjavalta.vaakuna.svg");
                City cHeinola = new City("Heinola", 17746, 675.97,
                                "Lake-filled city offering peaceful nature, sports, and wooden architecture.",
                                rPaijatHame,
                                "https://upload.wikimedia.org/wikipedia/commons/6/6f/Heinola.vaakuna.svg");
                City cHelsinki = new City("Helsinki", 689758, 214.58,
                                "Finland’s capital, combining coastal beauty, culture, and international life.",
                                rUusimaa,
                                "https://upload.wikimedia.org/wikipedia/commons/c/c4/Helsinki.vaakuna.svg");
                City cHuittinen = new City("Huittinen", 9618, 532.65,
                                "Small Satakunta city with agriculture, commerce, and relaxed lifestyle.", rSatakunta,
                                "https://upload.wikimedia.org/wikipedia/commons/0/0b/Huittisten.vaakuna.svg");
                City cHyvinkaa = new City("Hyvinkää", 47089, 322.71,
                                "Growing town with rail heritage, services, and nearby forests.", rUusimaa,
                                "https://upload.wikimedia.org/wikipedia/commons/3/34/Hyvinkaa.vaakuna.svg");
                City cHameenlinna = new City("Hämeenlinna", 68473, 1785.57,
                                "Historic city with Häme Castle, lakes, and cultural attractions.", rKantaHame,
                                "https://upload.wikimedia.org/wikipedia/commons/d/da/H%C3%A4meenlinna.vaakuna.svg");
                City cIisalmi = new City("Iisalmi", 20330, 763.01,
                                "North Savo town known for lakes, breweries, and relaxed vibe.", rPohjoisSavo,
                                "https://upload.wikimedia.org/wikipedia/commons/e/ed/Iisalmi.vaakuna.svg");
                City cIkaalinen = new City("Ikaalinen", 6713, 750.48,
                                "Spa town with lake views, forests, and cultural events.",
                                rPirkanmaa,
                                "https://upload.wikimedia.org/wikipedia/commons/e/ef/Ikaalinen.vaakuna.svg");
                City cImatra = new City("Imatra", 24581, 155.04,
                                "Industrial border city with famous rapids and lake scenery.",
                                rEtelaKarjala,
                                "https://upload.wikimedia.org/wikipedia/commons/6/60/Imatra.vaakuna.svg");
                City cJoensuu = new City("Joensuu", 78398, 2381.87,
                                "Eastern university city with Karelian culture and vibrant events.", rPohjoisKarjala,
                                "https://upload.wikimedia.org/wikipedia/commons/1/1d/Joensuu.vaakuna.svg");
                City cJyvaskyla = new City("Jyväskylä", 148744, 1171.03,
                                "Central Finland city known for education, architecture, and lakes.", rKeskiSuomi,
                                "https://upload.wikimedia.org/wikipedia/commons/9/93/Jyv%C3%A4skyl%C3%A4.vaakuna.svg");
                City cJamsa = new City("Jämsä", 19209, 1571.42,
                                "Lakeland town near Himos slopes, forests, and outdoor activities.", rKeskiSuomi,
                                "https://upload.wikimedia.org/wikipedia/commons/5/51/J%C3%A4ms%C3%A4nkoski.vaakuna.svg");
                City cJarvenpaa = new City("Järvenpää", 46942, 37.54,
                                "Compact cultural city tied to Sibelius and lakeside living.", rUusimaa,
                                "https://upload.wikimedia.org/wikipedia/commons/3/31/Jarvenpaa.vaakuna.svg");
                City cKaarina = new City("Kaarina", 36631, 150.64,
                                "Suburban coastal city near Turku with active communities.",
                                rVarsinaisSuomi,
                                "https://upload.wikimedia.org/wikipedia/commons/b/bf/Piikki%C3%B6.vaakuna.svg");
                City cKajaani = new City("Kajaani", 36458, 1835.09,
                                "Kainuu’s center with history, nature, and developing services.", rKainuu,
                                "https://upload.wikimedia.org/wikipedia/commons/a/ad/Kajaani.vaakuna.svg");
                City cKalajoki = new City("Kalajoki", 12231, 924.06,
                                "Known for long sandy beaches, tourism, and coastal landscapes.", rPohjoisPohjanmaa,
                                "https://upload.wikimedia.org/wikipedia/commons/7/77/Himanka.vaakuna.svg");
                City cKangasala = new City("Kangasala", 34315, 658.03, "Scenic ridge and lake area close to Tampere.",
                                rPirkanmaa,
                                "https://upload.wikimedia.org/wikipedia/commons/e/e1/Kangasala.vaakuna.svg");
                City cKankaanpaa = new City("Kankaanpää", 12571, 1021.24,
                                "Art-influenced town with forests, lakes, and active communities.", rSatakunta,
                                "https://upload.wikimedia.org/wikipedia/commons/d/df/Kankaanp%C3%A4%C3%A4.vaakuna.svg");
                City cKannus = new City("Kannus", 5255, 468.02,
                                "Small Central Ostrobothnian town with rural character and nature.", rKeskiPohjanmaa,
                                "https://upload.wikimedia.org/wikipedia/commons/2/25/Kannus.vaakuna.svg");
                City cKarkkila = new City("Karkkila", 8391, 242.44,
                                "Industrial town with forests, small lakes, and peaceful living.", rUusimaa,
                                "https://upload.wikimedia.org/wikipedia/commons/f/f8/Karkkila.vaakuna.svg");
                City cKaskinen = new City("Kaskinen", 1278, 10.64,
                                "Finland’s smallest city, coastal and calm with fishing traditions.", rPohjanmaa,
                                "https://upload.wikimedia.org/wikipedia/commons/c/c1/Kaskinen.vaakuna.svg");
                City cKauhajoki = new City("Kauhajoki", 12500, 1299.01,
                                "Agricultural South Ostrobothnian town with open plains.", rEtelaPohjanmaa,
                                "https://upload.wikimedia.org/wikipedia/commons/0/01/Kauhajoki.vaakuna.svg");
                City cKauhava = new City("Kauhava", 15066, 1313.85,
                                "Aviation heritage, rural landscapes, and strong craftsmanship traditions.",
                                rEtelaPohjanmaa,
                                "https://upload.wikimedia.org/wikipedia/commons/b/b3/Kauhava.vaakuna.2009.svg");
                City cKauniainen = new City("Kauniainen", 10200, 5.89,
                                "Affluent, park-filled small city surrounded by Espoo.",
                                rUusimaa, "https://upload.wikimedia.org/wikipedia/commons/6/6c/Kauniainen.vaakuna.svg");
                City cKemi = new City("Kemi", 19332, 95.38,
                                "Coastal Lapland city known for snow attractions and port activity.", rLappi,
                                "https://fi.wikipedia.org/wiki/Kemi#/media/Tiedosto:Kemi.vaakuna.svg");
                City cKemijarvi = new City("Kemijärvi", 6918, 3503.95,
                                "Lapland town with lakes, forests, and outdoor recreation.", rLappi,
                                "https://upload.wikimedia.org/wikipedia/commons/b/b6/Kemij%C3%A4rvi.vaakuna.svg");
                City cKerava = new City("Kerava", 38535, 30.64,
                                "Compact, rail-connected city with parks and active communities.", rUusimaa,
                                "https://upload.wikimedia.org/wikipedia/commons/8/87/Kerava.vaakuna.svg");
                City cKeuruu = new City("Keuruu", 9088, 1257.99,
                                "Lake-rich central town with history and peaceful landscapes.",
                                rKeskiSuomi, "https://upload.wikimedia.org/wikipedia/commons/5/5c/Keuruu.vaakuna.svg");
                City cKitee = new City("Kitee", 9483, 1253.81,
                                "North Karelian town with culture, lakes, and relaxed countryside.", rPohjoisKarjala,
                                "https://upload.wikimedia.org/wikipedia/commons/f/f1/Kitee.vaakuna.svg");
                City cKiuruvesi = new City("Kiuruvesi", 7338, 1328.32,
                                "Rural North Savo town known for agriculture and nature.", rPohjoisSavo,
                                "https://upload.wikimedia.org/wikipedia/commons/a/ab/Kiuruvesi.vaakuna.svg");
                City cKokemaki = new City("Kokemäki", 6662, 480.42,
                                "River town with history, fields, and peaceful rural life.",
                                rSatakunta,
                                "https://upload.wikimedia.org/wikipedia/commons/e/eb/Kokem%C3%A4ki.vaakuna.svg");
                City cKokkola = new City("Kokkola", 48361, 1446.38,
                                "Bilingual coastal city with old town heritage and maritime culture.", rKeskiPohjanmaa,
                                "https://upload.wikimedia.org/wikipedia/commons/1/1d/Kokkola.vaakuna.svg");
                City cKotka = new City("Kotka", 50157, 272.13,
                                "Port city with parks, maritime history, and island landscapes.",
                                rKymenlaakso, "https://upload.wikimedia.org/wikipedia/commons/1/13/Kotka.vaakuna.svg");
                City cKouvola = new City("Kouvola", 78094, 2557.61,
                                "Rail hub with forests, Repovesi park, and diverse neighborhoods.", rKymenlaakso,
                                "https://upload.wikimedia.org/wikipedia/commons/f/fa/Kouvola.vaakuna.2009.svg");
                City cKristiinankaupunki = new City("Kristiinankaupunki", 6131, 683.21,
                                "Well-preserved wooden coastal town with bilingual heritage.", rPohjanmaa,
                                "https://upload.wikimedia.org/wikipedia/commons/4/45/Kristiinankaupunki.vaakuna.svg");
                City cKuhmo = new City("Kuhmo", 7413, 4807.3,
                                "Wildlife-rich Kainuu town known for chamber music and wilderness.", rKainuu,
                                "https://upload.wikimedia.org/wikipedia/commons/e/e0/Kuhmo.vaakuna.svg");
                City cKuopio = new City("Kuopio", 125462, 3241.73,
                                "Lakeland city known for Puijo views, cuisine, and friendly culture.", rPohjoisSavo,
                                "https://upload.wikimedia.org/wikipedia/commons/c/cb/Kuopio.vaakuna.svg");
                City cKurikka = new City("Kurikka", 19474, 1724.77,
                                "South Ostrobothnian town with agriculture and strong local identity.", rEtelaPohjanmaa,
                                "https://upload.wikimedia.org/wikipedia/commons/a/a5/Kurikka.vaakuna.2009.svg");
                City cKuusamo = new City("Kuusamo", 14784, 4979.17,
                                "Outdoor destination with forests, hills, and nearby Ruka resort.", rPohjoisPohjanmaa,
                                "https://upload.wikimedia.org/wikipedia/commons/a/af/Kuusamo.vaakuna.svg");
                City cLahti = new City("Lahti", 121622, 459.55,
                                "Sports-focused city with lakes, design, and active urban life.", rPaijatHame,
                                "https://upload.wikimedia.org/wikipedia/commons/1/1a/Lahti.vaakuna.svg");
                City cLaitila = new City("Laitila", 8492, 532.02,
                                "Small southwest town with agriculture, industry, and rural calm.", rVarsinaisSuomi,
                                "https://upload.wikimedia.org/wikipedia/commons/6/6c/Laitila_vaakuna.svg");
                City cLappeenranta = new City("Lappeenranta", 72909, 1434.13,
                                "University city on Saimaa, known for fort, beaches, and culture.", rEtelaKarjala,
                                "https://upload.wikimedia.org/wikipedia/commons/f/f8/Lappeenranta.vaakuna.svg");
                City cLapua = new City("Lapua", 14016, 737.27,
                                "Ostrobothnian town with history, industry, and riverside scenery.", rEtelaPohjanmaa,
                                "https://upload.wikimedia.org/wikipedia/commons/6/60/Lapua.vaakuna.svg");
                City cLieksa = new City("Lieksa", 10002, 3417.74,
                                "Eastern town with forests, Koli nearby, and Karelian culture.", rPohjoisKarjala,
                                "https://upload.wikimedia.org/wikipedia/commons/9/90/Lieksa.vaakuna.svg");
                City cLieto = new City("Lieto", 20694, 300.53, "Growing community near Turku with rural landscapes.",
                                rVarsinaisSuomi,
                                "https://upload.wikimedia.org/wikipedia/commons/7/7d/Lieto_vaakuna.svg");
                City cLohja = new City("Lohja", 45686, 940.2,
                                "Lake-rich city with caves, orchards, and relaxed suburbs.",
                                rUusimaa, "https://upload.wikimedia.org/wikipedia/commons/b/b8/Lohja.vaakuna.svg");
                City cLoimaa = new City("Loimaa", 15248, 848.1,
                                "Agricultural town with fields, traditions, and small-city services.", rVarsinaisSuomi,
                                "https://upload.wikimedia.org/wikipedia/commons/a/a5/Loimaa.vaakuna.svg");
                City cLoviisa = new City("Loviisa", 14362, 820.06,
                                "Coastal town with wooden quarters, fortifications, and bilingual charm.", rUusimaa,
                                "https://upload.wikimedia.org/wikipedia/commons/b/b0/Loviisa.vaakuna.svg");
                City cMaarianhamina = new City("Maarianhamina", 11898, 11.83,
                                "Åland’s capital with maritime life, ports, and compact city center.", rAhvenanmaa,
                                "https://upload.wikimedia.org/wikipedia/commons/7/79/Maarianhamina.vaakuna.svg");
                City cMikkeli = new City("Mikkeli", 51661, 2548.37,
                                "Lakeland city with outdoor recreation, history, and Saimaa views.", rEtelaSavo,
                                "https://upload.wikimedia.org/wikipedia/commons/0/09/Mikkeli.vaakuna.svg");
                City cManttaVilppula = new City("Mänttä-Vilppula", 9234, 534.78,
                                "Art-friendly town with lakes, industry, and cultural centers.", rPirkanmaa,
                                "https://upload.wikimedia.org/wikipedia/commons/a/ad/Vilppula.vaakuna.svg");
                City cNaantali = new City("Naantali", 20312, 312.9,
                                "Famous for old town, spa culture, and Moominworld.",
                                rVarsinaisSuomi,
                                "https://upload.wikimedia.org/wikipedia/commons/b/ba/Naantali.vaakuna.svg");
                City cNivala = new City("Nivala", 10397, 527.35,
                                "Northern rural town with industry, agriculture, and calm living.", rPohjoisPohjanmaa,
                                "https://upload.wikimedia.org/wikipedia/commons/9/94/Nivala.vaakuna.svg");
                City cNokia = new City("Nokia", 36486, 288.34,
                                "Industrial town near Tampere with lakes and growing services.",
                                rPirkanmaa, "https://upload.wikimedia.org/wikipedia/commons/2/26/Nokia.vaakuna.svg");
                City cNurmes = new City("Nurmes", 8924, 2401.59,
                                "Karelian-influenced town with hills, lakes, and quiet nature.", rPohjoisKarjala,
                                "https://upload.wikimedia.org/wikipedia/commons/8/85/Nurmes.vaakuna.svg");
                City cNarpio = new City("Närpiö", 9559, 977.77,
                                "Coastal bilingual town known for greenhouses and agriculture.",
                                rPohjanmaa,
                                "https://upload.wikimedia.org/wikipedia/commons/7/7a/N%C3%A4rpi%C3%B6.vaakuna.svg");
                City cOrimattila = new City("Orimattila", 15628, 785.38,
                                "Southern rural town with fields, forests, and active communities.", rPaijatHame,
                                "https://upload.wikimedia.org/wikipedia/commons/6/68/Orimattila.vaakuna.svg");
                City cOrivesi = new City("Orivesi", 8860, 799.74,
                                "Forested lakeside town near Tampere with arts and outdoor life.", rPirkanmaa,
                                "https://upload.wikimedia.org/wikipedia/commons/f/f0/Orivesi.vaakuna.svg");
                City cOulainen = new City("Oulainen", 6887, 587.47,
                                "Small northern town with industry and peaceful rural surroundings.", rPohjoisPohjanmaa,
                                "https://upload.wikimedia.org/wikipedia/commons/0/05/Oulainen.vaakuna.svg");
                City cOulu = new City("Oulu", 216066, 2972.39,
                                "Northern hub known for tech, culture, and seaside city life.",
                                rPohjoisPohjanmaa,
                                "https://upload.wikimedia.org/wikipedia/commons/3/36/Oulu.vaakuna.svg");
                City cOutokumpu = new City("Outokumpu", 6404, 446.25,
                                "Mining heritage town surrounded by forests and lakes.",
                                rPohjoisKarjala,
                                "https://upload.wikimedia.org/wikipedia/commons/4/47/Outokumpu.vaakuna.svg");
                City cPaimio = new City("Paimio", 11241, 238.52,
                                "Known for Alvar Aalto architecture, forests, and quiet living.", rVarsinaisSuomi,
                                "https://upload.wikimedia.org/wikipedia/commons/9/99/Paimio_vaakuna.svg");
                City cParainen = new City("Parainen", 14814, 884.67,
                                "Archipelago city with maritime culture and bilingual heritage.", rVarsinaisSuomi,
                                "https://upload.wikimedia.org/wikipedia/commons/1/1a/Nagu.vapen.Nauvo.vaakuna.svg");
                City cParkano = new City("Parkano", 6092, 852.91,
                                "Forest town near borders of regions, known for nature.",
                                rPirkanmaa, "https://upload.wikimedia.org/wikipedia/commons/8/85/Parkano.vaakuna.svg");
                City cPieksamaki = new City("Pieksämäki", 17243, 1569,
                                "Rail-crossing Lakeland town with lakes and relaxed atmosphere.", rEtelaSavo,
                                "https://upload.wikimedia.org/wikipedia/commons/7/71/Pieks%C3%A4m%C3%A4ki.vaakuna.svg");
                City cPietarsaari = new City("Pietarsaari", 19668, 88.38,
                                "Bilingual coastal city with wooden districts and maritime heritage.", rPohjanmaa,
                                "https://upload.wikimedia.org/wikipedia/commons/a/a4/Pietarsaari.vaakuna.svg");
                City cPori = new City("Pori", 83157, 1156.49, "Coastal city famous for jazz, beaches, and industry.",
                                rSatakunta, "https://upload.wikimedia.org/wikipedia/commons/c/cb/Porin_vaakuna.svg");
                City cPorvoo = new City("Porvoo", 51853, 654.92,
                                "Historic city with old town, river scenery, and bilingual life.", rUusimaa,
                                "https://upload.wikimedia.org/wikipedia/commons/3/3a/Porvoo.vaakuna.svg");
                City cPudasjarvi = new City("Pudasjärvi", 7226, 5638.52,
                                "Large wilderness area with forests, hills, and outdoor activities.", rPohjoisPohjanmaa,
                                "https://upload.wikimedia.org/wikipedia/commons/a/ae/Pudasjarvi.vaakuna.svg");
                City cPyhajarvi = new City("Pyhäjärvi", 4639, 1310.32,
                                "Small mining-influenced town with lakes and rural calm.", rPohjoisPohjanmaa,
                                "https://upload.wikimedia.org/wikipedia/commons/5/53/Pyh%C3%A4j%C3%A4rvi.vaakuna.svg");
                City cRaahe = new City("Raahe", 23566, 1013.79,
                                "Coastal metal-industry city with preserved wooden old town.",
                                rPohjoisPohjanmaa,
                                "https://upload.wikimedia.org/wikipedia/commons/d/d3/Raahe.vaakuna.svg");
                City cRaasepori = new City("Raasepori", 27002, 1152.14,
                                "Coastal, bilingual area with castles, towns, and archipelago.", rUusimaa,
                                "https://upload.wikimedia.org/wikipedia/commons/9/9d/Raasepori.vaakuna.svg");
                City cRaisio = new City("Raisio", 25846, 48.8,
                                "Commercial town near Turku with industry and suburban living.",
                                rVarsinaisSuomi,
                                "https://upload.wikimedia.org/wikipedia/commons/d/d5/Raisio.vaakuna.svg");
                City cRauma = new City("Rauma", 38909, 496.3, "Known for lace tradition, old wooden town, and port.",
                                rSatakunta, "https://upload.wikimedia.org/wikipedia/commons/d/d8/Rauma.vaakuna.svg");
                City cRiihimaki = new City("Riihimäki", 28610, 121.01,
                                "Rail city with museums, industry, and central location.", rKantaHame,
                                "https://upload.wikimedia.org/wikipedia/commons/2/2b/Riihim%C3%A4ki.vaakuna.svg");
                City cRovaniemi = new City("Rovaniemi", 65670, 7581.53,
                                "Arctic city, Santa Claus attractions, and northern wilderness.", rLappi,
                                "https://upload.wikimedia.org/wikipedia/commons/c/c9/Rovaniemi.vaakuna.svg");
                City cSaarijarvi = new City("Saarijärvi", 8831, 1251.76,
                                "Central lake district town with hills and peaceful nature.", rKeskiSuomi,
                                "https://upload.wikimedia.org/wikipedia/commons/e/e4/Saarij%C3%A4rvi.vaakuna.svg");
                City cSalo = new City("Salo", 50794, 1989.77,
                                "Tech-influenced city between Turku and Helsinki with rural surroundings.",
                                rVarsinaisSuomi,
                                "https://upload.wikimedia.org/wikipedia/commons/5/5e/Halikko_vaakuna.svg");
                City cSastamala = new City("Sastamala", 23444, 1429.12,
                                "Literary town with lakes, countryside, and historic churches.", rPirkanmaa,
                                "https://upload.wikimedia.org/wikipedia/commons/f/f5/Karkku.vaakuna.svg");
                City cSavonlinna = new City("Savonlinna", 31283, 2238,
                                "Lake Saimaa city known for Olavinlinna and opera festival.", rEtelaSavo,
                                "https://upload.wikimedia.org/wikipedia/commons/9/97/Savonlinna.vaakuna.svg");
                City cSeinajoki = new City("Seinäjoki", 66848, 1431.59,
                                "Dynamic Ostrobothnian city with events, architecture, and plains.", rEtelaPohjanmaa,
                                "https://upload.wikimedia.org/wikipedia/commons/4/4e/Sein%C3%A4joki.vaakuna.svg");
                City cSomero = new City("Somero", 8423, 668.06,
                                "Rural southwest town known for culture, agriculture, and lake areas.", rVarsinaisSuomi,
                                "https://upload.wikimedia.org/wikipedia/commons/5/5d/Somero.vaakuna.svg");
                City cSuonenjoki = new City("Suonenjoki", 6615, 713.56,
                                "Strawberry-centered town in North Savo with lakes and forests.", rPohjoisSavo,
                                "https://upload.wikimedia.org/wikipedia/commons/8/80/Suonenjoki_coat_of_arms.svg");
                City cTampere = new City("Tampere", 260646, 526.16,
                                "Lively industrial-heritage city with lakes, culture, and innovation.", rPirkanmaa,
                                "https://upload.wikimedia.org/wikipedia/commons/9/9f/Tampere.vaakuna.svg");
                City cTornio = new City("Tornio", 20932, 1188.74,
                                "Border city with Haparanda, industry, and coastal landscapes.", rLappi,
                                "https://upload.wikimedia.org/wikipedia/commons/e/e9/Tornio.vaakuna.svg");
                City cTurku = new City("Turku", 206655, 245.85,
                                "Historic southwest city with river life, culture, and archipelago.", rVarsinaisSuomi,
                                "https://upload.wikimedia.org/wikipedia/commons/d/d7/Turku.vaakuna.svg");
                City cUlvila = new City("Ulvila", 12345, 400.84,
                                "Small Satakunta town with history, suburbs, and peaceful living.", rSatakunta,
                                "https://upload.wikimedia.org/wikipedia/commons/a/a8/Ulvila.vaakuna.svg");
                City cUusikaarlepyy = new City("Uusikaarlepyy", 7462, 732.86,
                                "Bilingual coastal town with rivers, tradition, and calm charm.", rPohjanmaa,
                                "https://upload.wikimedia.org/wikipedia/commons/7/7c/Uusikaarlepyy.vaakuna.svg");
                City cUusikaupunki = new City("Uusikaupunki", 14750, 504.33,
                                "Coastal city with shipbuilding, old wooden areas, and archipelago.", rVarsinaisSuomi,
                                "https://upload.wikimedia.org/wikipedia/commons/f/fa/Uusikaupunki.vaakuna.svg");
                City cVaasa = new City("Vaasa", 69819, 364.88,
                                "Bilingual coastal city with universities, energy industry, and seafront.", rPohjanmaa,
                                "https://upload.wikimedia.org/wikipedia/commons/1/1f/Vaasa.vaakuna2.svg");
                City cValkeakoski = new City("Valkeakoski", 20859, 272.08,
                                "Industrial town with canals, sports culture, and lake scenery.", rPirkanmaa,
                                "https://fi.wikipedia.org/wiki/Valkeakoski#/media/Tiedosto:Valkeakoski.vaakuna.svg");
                City cVantaa = new City("Vantaa", 252724, 238.39,
                                "Airport city with diverse districts, nature, and growing services.", rUusimaa,
                                "https://upload.wikimedia.org/wikipedia/commons/4/40/Vantaa.vaakuna.svg");
                City cVarkaus = new City("Varkaus", 19603, 385.62,
                                "Industrial lakeside town with canals, culture, and relaxed pace.", rPohjoisSavo,
                                "https://upload.wikimedia.org/wikipedia/commons/8/8f/Varkaus.vaakuna.svg");
                City cViitasaari = new City("Viitasaari", 5787, 1248.53,
                                "Central lake-and-hill town focused on nature and outdoor life.", rKeskiSuomi,
                                "https://upload.wikimedia.org/wikipedia/commons/2/2e/Viitasaari.vaakuna.svg");
                City cVirrat = new City("Virrat", 6165, 1162.52,
                                "Forested lake region town with quiet rural atmosphere.",
                                rPirkanmaa, "https://upload.wikimedia.org/wikipedia/commons/a/ae/Virrat.vaakuna.svg");
                City cYlivieska = new City("Ylivieska", 15375, 569.84,
                                "Northern service and trade town with steady growth.",
                                rPohjoisPohjanmaa,
                                "https://upload.wikimedia.org/wikipedia/commons/9/91/Ylivieska.vaakuna.svg");
                City cYlojarvi = new City("Ylöjärvi", 33731, 1115.75,
                                "Growing Tampere-area town with lakes, forests, and suburban life.", rPirkanmaa,
                                "https://upload.wikimedia.org/wikipedia/commons/a/af/Yl%C3%B6j%C3%A4rvi.vaakuna.svg");
                City cAhtari = new City("Ähtäri", 5180, 805.79,
                                "Known for zoo, forests, and peaceful lakeside landscapes.",
                                rEtelaPohjanmaa,
                                "https://upload.wikimedia.org/wikipedia/commons/f/f9/%C3%84ht%C3%A4ri.vaakuna.svg");
                City cAanekoski = new City("Äänekoski", 17614, 884.61,
                                "Industrial lakeside town in Central Finland with scenic nature.", rKeskiSuomi,
                                "https://upload.wikimedia.org/wikipedia/commons/a/a3/%C3%84%C3%A4nekoski.vaakuna.svg");

                AppUser appUser1 = new AppUser("admin", "$2a$10$zNXa3MgyyUslVl.jL8950eGswQKEBKFVkSXlvghOPigjUcKXsasbK",
                                "ADMIN",
                                "adminTest", "userTestLast");
                AppUser appUser2 = new AppUser("user", "$2a$10$YxQApzp3QttDxZO2Mx1BbeyQHH9YJaLDMciTk0zI/yiULbTJVZq/C",
                                "USER",
                                "userTest", "userTestLast");
                AppUser appUser3 = new AppUser("erkki", "$2a$10$DS/qbwxu.pxDNcvaFC4IS.00fnAovXseaUnqu/ccE5DBBoLpWUile",
                                "USER",
                                "Erkki", "Esimerkki");
                AppUser appUser4 = new AppUser("pekka", "$2a$10$a1O0jjIa9HUB7Zr1rMkmY.qU0OuPj9XRlkCEoiS6CtGYcDWi3f2rK",
                                "USER",
                                "Pekka");
                AppUser appUser5 = new AppUser("maintenance",
                                "$2a$10$WUfrNQVubEAoZdPE/D8Qkue2ApFz4DzXlR3AUop/RYYG9u1Xp1dfy", "ADMIN");

                City city1 = new City("Cmd: Test City 1", 210542, 80.55, "A city in need is a city indeed", region1);
                String lorem = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin luctus lorem et erat malesuada efficitur. Praesent convallis accumsan risus, at feugiat diam feugiat ullamcorper. Mauris varius ligula eros, nec mattis dui laoreet vel.";
                City city2 = new City("Cmd: Test City 2", 55004, 65.55, lorem, region1);
                Location location1 = new Location("Cmd: Test Location 1", city1);
                Location location2 = new Location("Cmd: Test Location 2", "A lovely location indeed", city2);
                Comment comment1 = new Comment("Test headline", "A testful body of text", location1, appUser1);
                Comment comment2 = new Comment("Test headline", "A testful body of text", location2, appUser2);
                Comment comment3 = new Comment("Test headline", "A testful body of text", location1, appUser3);
                Comment comment4 = new Comment("Test headline", "A testful body of text", location1, appUser2);
                rRepository.save(rAhvenanmaa);
                rRepository.save(rEtelaKarjala);
                rRepository.save(rEtelaPohjanmaa);
                rRepository.save(rEtelaSavo);
                rRepository.save(rKainuu);
                rRepository.save(rKantaHame);
                rRepository.save(rKeskiPohjanmaa);
                rRepository.save(rKeskiSuomi);
                rRepository.save(rKymenlaakso);
                rRepository.save(rLappi);
                rRepository.save(rPirkanmaa);
                rRepository.save(rPohjanmaa);
                rRepository.save(rPohjoisKarjala);
                rRepository.save(rPohjoisPohjanmaa);
                rRepository.save(rPohjoisSavo);
                rRepository.save(rPaijatHame);
                rRepository.save(rSatakunta);
                rRepository.save(rUusimaa);
                rRepository.save(rVarsinaisSuomi);

                cRepository.save(cAkaa);
                cRepository.save(cAlajarvi);
                cRepository.save(cAlavus);
                cRepository.save(cEspoo);
                cRepository.save(cForssa);
                cRepository.save(cHaapajarvi);
                cRepository.save(cHaapavesi);
                cRepository.save(cHamina);
                cRepository.save(cHanko);
                cRepository.save(cHarjavalta);
                cRepository.save(cHeinola);
                cRepository.save(cHelsinki);
                cRepository.save(cHuittinen);
                cRepository.save(cHyvinkaa);
                cRepository.save(cHameenlinna);
                cRepository.save(cIisalmi);
                cRepository.save(cIkaalinen);
                cRepository.save(cImatra);
                cRepository.save(cJoensuu);
                cRepository.save(cJyvaskyla);
                cRepository.save(cJamsa);
                cRepository.save(cJarvenpaa);
                cRepository.save(cKaarina);
                cRepository.save(cKajaani);
                cRepository.save(cKalajoki);
                cRepository.save(cKangasala);
                cRepository.save(cKankaanpaa);
                cRepository.save(cKannus);
                cRepository.save(cKarkkila);
                cRepository.save(cKaskinen);
                cRepository.save(cKauhajoki);
                cRepository.save(cKauhava);
                cRepository.save(cKauniainen);
                cRepository.save(cKemi);
                cRepository.save(cKemijarvi);
                cRepository.save(cKerava);
                cRepository.save(cKeuruu);
                cRepository.save(cKitee);
                cRepository.save(cKiuruvesi);
                cRepository.save(cKokemaki);
                cRepository.save(cKokkola);
                cRepository.save(cKotka);
                cRepository.save(cKouvola);
                cRepository.save(cKristiinankaupunki);
                cRepository.save(cKuhmo);
                cRepository.save(cKuopio);
                cRepository.save(cKurikka);
                cRepository.save(cKuusamo);
                cRepository.save(cLahti);
                cRepository.save(cLaitila);
                cRepository.save(cLappeenranta);
                cRepository.save(cLapua);
                cRepository.save(cLieksa);
                cRepository.save(cLieto);
                cRepository.save(cLohja);
                cRepository.save(cLoimaa);
                cRepository.save(cLoviisa);
                cRepository.save(cMaarianhamina);
                cRepository.save(cMikkeli);
                cRepository.save(cManttaVilppula);
                cRepository.save(cNaantali);
                cRepository.save(cNivala);
                cRepository.save(cNokia);
                cRepository.save(cNurmes);
                cRepository.save(cNarpio);
                cRepository.save(cOrimattila);
                cRepository.save(cOrivesi);
                cRepository.save(cOulainen);
                cRepository.save(cOulu);
                cRepository.save(cOutokumpu);
                cRepository.save(cPaimio);
                cRepository.save(cParainen);
                cRepository.save(cParkano);
                cRepository.save(cPieksamaki);
                cRepository.save(cPietarsaari);
                cRepository.save(cPori);
                cRepository.save(cPorvoo);
                cRepository.save(cPudasjarvi);
                cRepository.save(cPyhajarvi);
                cRepository.save(cRaahe);
                cRepository.save(cRaasepori);
                cRepository.save(cRaisio);
                cRepository.save(cRauma);
                cRepository.save(cRiihimaki);
                cRepository.save(cRovaniemi);
                cRepository.save(cSaarijarvi);
                cRepository.save(cSalo);
                cRepository.save(cSastamala);
                cRepository.save(cSavonlinna);
                cRepository.save(cSeinajoki);
                cRepository.save(cSomero);
                cRepository.save(cSuonenjoki);
                cRepository.save(cTampere);
                cRepository.save(cTornio);
                cRepository.save(cTurku);
                cRepository.save(cUlvila);
                cRepository.save(cUusikaarlepyy);
                cRepository.save(cUusikaupunki);
                cRepository.save(cVaasa);
                cRepository.save(cValkeakoski);
                cRepository.save(cVantaa);
                cRepository.save(cVarkaus);
                cRepository.save(cViitasaari);
                cRepository.save(cVirrat);
                cRepository.save(cYlivieska);
                cRepository.save(cYlojarvi);
                cRepository.save(cAhtari);
                cRepository.save(cAanekoski);
                auRepository.save(appUser1);
                auRepository.save(appUser2);
                auRepository.save(appUser3);
                auRepository.save(appUser4);
                auRepository.save(appUser5);

                rRepository.save(region1);
                rRepository.save(region2);
                cRepository.save(city1);
                cRepository.save(city2);
                lRepository.save(location1);
                lRepository.save(location2);
                coRepository.save(comment1);
                coRepository.save(comment2);
                coRepository.save(comment3);
                coRepository.save(comment4);

                return "redirect:" + referer;
        }

}
